server:
  port: 8080
  # Do not set the contextPath as we are building our GraphQl API in the same project as the REST API.
  # otherwise, the default GraphQl path would be: /api/v1/graphql instead of /graphql
  # contextPath: /api/v1

# Update the following configuration if you need custom behaviour for your GraphQl API:
#graphql:
#  servlet:
#    mapping: /graphql
#    enabled: true
#    corsEnabled: true

#graphiql:
#  mapping: /graphiql
#  endpoint: /graphql
#  enabled: true

###
#   Database Settings
###
spring:
  datasource:
    url: jdbc:h2:mem:tv-show-rest-vs-graphql-api-app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        show_sql: true
        use_sql_comments: true
        format_sql: true

###
#   H2 Settings
###
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
